name: Build Resume

on:
  push:
    branches: [ main ]
    paths:
      - resume.json
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install resume-cli and theme
        run: |
          npm install -g resume-cli
          npm install jsonresume-theme-even

      - name: Build PDF and HTML
        run: |
          resume export cv.pdf --theme ./node_modules/jsonresume-theme-even/dist
          resume export cv.html --theme ./node_modules/jsonresume-theme-even/dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: |
            cv.pdf
            cv.html
